name: Build

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  mac:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update Submodules
        run: |
          git submodule update --recursive --remote
      - name: Commit Update
        uses: stefanzweifel/git-auto-commit-action@v5
      # 后面对文件可能进行修改，不要在这里commit 
      # 设置环境变量
      - name: Get aria2 latset commit ID
        run: |
          cd aria2-git
          echo "cache-name=$(git rev-parse HEAD)" >> ../aria2-hash.txt
          brew install tree
          tree
      - name: Cache aria2
        id: cache
        uses: actions/cache@v3
        with:
          path: aria2-git
          key: ${{ runner.os }}-aria2-${{ env.cache-name }}-${{ hashFiles('aria2-hash.txt') }}
          restore-keys: |
            ${{ runner.os }}-aria2-${{ env.cache-name }}-
            ${{ runner.os }}-aria2-
            ${{ runner.os }}-
      - if: steps.cache.outputs.cache-hit != 'true'
        name: Compile aria2
        run: |
          cd aria2-git
          brew install libxml2 libcpuid autoconf automake atool libtool
          autoreconf -i
          ./configure ARIA2_STATIC=yes
          make
      - name: Copy aria2c
        run: |
          cd aria2-git
          cp src/aria2c ../aria2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - name: Install macos dependencies
        run: |
          brew install create-dmg
          brew install python-tk
          brew install aria2
      - name: Build MacOS application
        run : |
          pyinstaller --add-data './aria2/aria2c:./aria2' -n "SJTU-Canvas视频下载器" -w  --icon=icons/canvas.icns main.py 
          mkdir -p dist/dmg
          cp -r dist/SJTU-Canvas视频下载器.app dist/dmg
      - name: Create dmg
        run : 
          create-dmg --volname "SJTU-Canvas视频下载器" --background "icons/background.png" --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon SJTU-Canvas视频下载器.app 200 190 --hide-extension SJTU-Canvas视频下载器.app --app-drop-link 600 185 "dist/SJTU-Canvas视频下载器.dmg" "dist/dmg/" 
      - name: Upload dmg
        uses: actions/upload-artifact@v3.1.2
        with:
          name: canvas-downloader-macos.dmg
          path: "dist/SJTU-Canvas视频下载器.dmg"
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip3 install -r requirements.txt
      - run: pyinstaller main.py
      - run: xcopy aria2\ dist\main\aria2\ /e /i /y
      - uses: actions/upload-artifact@v3
        with:
          name: canvas-downloader-win.zip
          path: dist/main/
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: pyinstaller main.py
      - uses: actions/upload-artifact@v3
        with:
          name: canvas-downloader-linux.zip
          path: dist/main/

      # - run: Compress-Archive dist\main\* windows.zip
      # - id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.event.repository.pushed_at}}
      #     release_name: ${{ github.event.repository.pushed_at}}
      # - uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: windows.zip
      #     asset_name: windows.zip
      #     asset_content_type: application/zip